services:


#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    patient_service:
        class: Utils\PatientService
        arguments: ['@doctrine.orm.entity_manager', '@jms_serializer', '@validator' , '@service_container']
        public: true
    
    therapist_service:
        class: Utils\TherapistService
        arguments: ['@doctrine.orm.entity_manager', '@jms_serializer', '@validator' , '@service_container']
        public: true